name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.14.4

    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout all history for all branches and tags
        fetch-depth: 0
    - name: Install rebar3
      run:  mix local.rebar --force
    - name: Install hex
      run:  mix local.hex --force
    - name: Compile
      run:  make
    - name: Compile
      run:  mix do deps.get, deps.compile
    - name: Run tests
      run:  mix bench
